#!/usr/bin/env ruby

require "csv"

DIR_PATH = File.expand_path("~/.tt")

def init
	system("mkdir", "-p", DIR_PATH) unless Dir.exist?(DIR_PATH)

	header = %w(id type reference timestamp name)

	CSV.open("#{DIR_PATH}/active.csv", "wb") do |csv|
		csv << header
	end

	CSV.open("#{DIR_PATH}/db.csv", "wb") do |csv|
		csv << header
	end
end

case ARGV.first
when nil
	# default
	exit
when "init"
	init
	exit
else
	puts "tt: command not found: #{ARGV.first}"
	exit 1
end

