#!/usr/bin/env ruby

require_relative "db"
require_relative "initializer"

DIR_PATH = File.expand_path("~/.tt")

@db = DB.new

def start
  print "name: "
  name = $stdin.gets.chomp
  now = Time.now
  @db.start(
    id: now.hash,
    type: "start",
    reference: nil,
    timestamp: now,
    name: name
  )
end

case ARGV.first
when nil
	# default
	exit
when "init"
  Initializer.init
	exit
when "start"
	start
	exit
else
	puts "tt: command not found: #{ARGV.first}"
	exit 1
end

